TrainingConfig:
  config_path: /mnt/qb/work/ludwig/lqb122/temporal_sr/configs/DDIM_config.yaml
  data_path: /mnt/qb/work/ludwig/lqb122/data/all_years_merged_era5.nc
  edsr: false
  eval_batch_size: 1
  feature_list:
  - u10
  - v10
  - t2m
  - d2m
  - msl
  - tp
  gradient_accumulation_steps: 1
  hub_model_id: bela
  hub_private_repo: true
  in_channels: 12
  learning_rate: 0.0001
  lr_warmup_steps: 50
  mean_d2m: 0.5075131058692932
  mean_msl: 0.5703748464584351
  mean_t2m: 0.4832382798194885
  mean_tp: 0.5661574006080627
  mean_u10: 0.47303104400634766
  mean_v10: 0.4797371029853821
  mixed_precision: fp16
  model_path: /mnt/qb/work/ludwig/lqb122/temporal_sr/DDIM/models/models_80_83
  num_eval_timesteps: 50
  num_images_per_cond: 15
  num_train_epochs: 200
  num_train_timesteps: 1000
  out_channels: 3
  output_dir: /mnt/qb/work/ludwig/lqb122/temporal_sr/DDIM/outputs/output_80_83
  overwrite_outputdir: true
  patch_size: 32
  preds_dir: /mnt/qb/work/ludwig/lqb122/temporal_sr/DDIM/preds/preds_80_83
  pretraining: true
  push_to_hub: false
  random_years:
  - 1980
  - 1994
  - 1993
  save_image_epochs: 1
  save_model_epochs: 1
  scaling_factor: 4
  seed: 0
  sequence_length: 3
  std_d2m: 0.11949099600315094
  std_msl: 0.1007150411605835
  std_t2m: 0.12425408512353897
  std_tp: 0.14186809957027435
  std_u10: 0.11790993809700012
  std_v10: 0.12059098482131958
  test_year_pretraining: 1983
  test_years_end: 2023
  test_years_start: 1984
  train_batch_size: 16
  train_end_date: '1982-12-31'
  train_start_date: '1980-01-01'
  use_random_years: false
  weight_decay: 1.0e-05
