TrainingConfig:
  config_path: /mnt/qb/work/ludwig/lqb122/temporal_sr/configs/EDSR_config.yaml
  data_path: /mnt/qb/work/ludwig/lqb122/data/merge_atlantic_data.nc
  eval_batch_size: 1
  feature_channels: 64
  feature_list:
  - u10
  - v10
  - t2m
  - d2m
  - msl
  - tp
  in_channels: 3
  mean_d2m: 0.4396512806415558
  mean_msl: 0.4387790262699127
  mean_t2m: 0.5215343832969666
  mean_tp: 0.4729074537754059
  mean_u10: 0.5115142464637756
  mean_v10: 0.5123587846755981
  model_path: /mnt/qb/work/ludwig/lqb122/temporal_sr/EDSR/models/models_atlantic
  num_train_epochs: 100
  out_channels: 3
  output_dir: /mnt/qb/work/ludwig/lqb122/temporal_sr/EDSR/outputs/output_atlantic
  patch_size: 32
  preds_dir: /mnt/qb/work/ludwig/lqb122/temporal_sr/EDSR/preds/preds_atlantic
  pretraining: false
  random_years:
  - 1980
  - 1994
  - 1993
  scaling_factor: 8
  std_d2m: 0.2310042679309845
  std_msl: 0.23173673450946808
  std_t2m: 0.13607747852802277
  std_tp: 0.24947123229503632
  std_u10: 0.13409052789211273
  std_v10: 0.13615688681602478
  test_year_pretraining: 1983
  test_years_end: 2023
  test_years_start: 1984
  train_batch_size: 16
  train_end_date: '1982-12-31'
  train_start_date: '1980-01-01'
  use_random_years: false
