TrainingConfig:
  config_path: /home/bela/thesis/temporal_sr/local_config.yaml
  data_path: /home/bela/thesis/data/merge_atlantic_data.nc
  eval_batch_size: 1
  feature_channels: 64
  feature_list:
  - u10
  - v10
  - t2m
  - d2m
  - msl
  - tp
  in_channels: 3
  mean_d2m: 271.56866455078125
  mean_msl: 100409.0234375
  mean_t2m: 273.1571044921875
  mean_tp: 0.00010626256698742509
  mean_u10: 0.4288536608219147
  mean_v10: 0.43577271699905396
  model_path: /home/bela/thesis/temporal_sr/EDSR/model
  num_train_epochs: 10
  out_channels: 3
  output_dir: /home/bela/thesis/preds
  patch_size: 32
  preds_dir: /home/bela/thesis/temporal_sr/EDSR/preds
  scaling_factor: 8
  test_end_date: '1989-12-31'
  test_start_date: '1989-01-01'
  train_batch_size: 16
  train_end_date: '1982-12-31'
  train_start_date: '1980-01-01'
